### ISSUE TITLE
Use of run_pfam_scan.sh

### ISSUE THREAD

**Issue by awixom18** [krasileva-group/plant_rgenes#1]
Hello,

I'm attempting to use your scripts to follow the protocols described in 'Comparative analysis of plant immune receptor architectures uncovers host proteins likely targeted by pathogens' and I am getting some odd errors when I run this on my plant sequences. 

Specifically:
Use of uninitialized value in numeric ge (>=) at PfamScan/Bio/Pfam/Scan/PfamScan.pm line 210.
Use of uninitialized value in numeric ge (>=) at PfamScan/Bio/Pfam/Scan/PfamScan.pm line 213.
Use of uninitialized value in printf at PfamScan/Bio/Pfam/HMM/HMMResultsIO.pm line 1131.

I'm unfortunately unexperienced enough with scripts to be able to know whats going on. These errors are stated thousands of times in the terminal window. Please let me know if I can provide any other information to help resolve this problem.

Alex Wixom

**Comment by krasileva** [comment]
Hi Alex,

Which script are you using? Could you give me your full command?

Best wishes,

Ksenia

Ksenia V Krasileva

**Comment by awixom18** [comment]
I'm using the run_pfam_scan.sh script with the command:

./bash_scripts/run_pfam_scan.sh ./master_dir/ ~/pfamA/

While thinking about this over the weekend, I noticed that I am using Hmmer 3.1 and the pfamscan.pl script (version 1.5) that was written to work with Hmmer 3.1. It appears that Hmmer 2.0 was used in your paper... Could these be the causes of the issues?

As a side note, when I downloaded run_pfam_scan.sh there was a missing "$2" argument for the location of the Pfam directory in the command. I also had to delete out the -pfamB flag within the run_pfam_scan.sh input into the pfamscan.pl script due to the new version not allowing it and causing a fatal error.

From the output command file:
'time perl pfam_scan.pl -e_seq 1 -e_dom 1 -as -outfile ./master_dir//Ssisymbriifolium/pfam/Ssisymbrifolium_translated99_pfamscan-02-23-2016.out -cpu 8 -fasta ./master_dir//Ssisymbriifolium/Ssisymbrifolium_translated99_protein.fa -dir /Users/NotPCN/pfamA/'

Let me know if there is anything else I can do.

Cheers,

Alex

**Comment by krasileva** [comment]
I think I know what is happening.

I was not passing pfam as $2, but I used to hardcode it in the script, ie

Pfam=/Volumes/DATA1/db/Pfam

If you are passing it as command script, you should still pass the
~/pfamA/Pfam or equivalent.

Cheers,

Ksenia

Ksenia

**Comment by awixom18** [comment]
Ahh. Excellent. Got it to work. Thanks for your help!
